Cleanny/Cleanny.xcodeproj/project.pbxproj
Cleanny/Cleanny.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Cleanny/Cleanny/Assets.xcassets/Primary.colorset/Contents.json
Cleanny/Cleanny/Assets.xcassets/Secondary.colorset/Contents.json
Cleanny/Cleanny/Pages/CharacterView.swift
Cleanny/Cleanny/Pages/ChartView.swift
Cleanny/Cleanny/Pages/CircularProgressView.swift
Cleanny/Cleanny/Pages/RecordView.swift

created circleProgress in characterView

Add CircleProgress

---

Cleanny/Cleanny.xcodeproj/project.pbxproj
Cleanny/Cleanny/Pages/CharacterView.swift
Cleanny/Cleanny/Pages/CircularProgressBarView.swift
Cleanny/Cleanny/Pages/CircularProgressView.swift

- 메인 회색원과 gradient progressBar분리
- 주석추가

refactor: Circular ProgressBar

---

Cleanny/Cleanny/Pages/CharacterView.swift

Update: CharacterView Background Color 적용

---

Cleanny/Cleanny.xcodeproj/project.pbxproj
Cleanny/Cleanny/Assets.xcassets/Color set/SBlue.colorset/Contents.json
Cleanny/Cleanny/CleaningCategory.swift
Cleanny/Cleanny/CleaningCategoryList.json
Cleanny/Cleanny/ModelData.swift
Cleanny/Cleanny/Pages/CleaningCategoryView.swift
Cleanny/Cleanny/Pages/SettingCard.swift
Cleanny/Cleanny/Pages/SettingModalView.swift
Cleanny/Cleanny/Pages/SettingSlider.swift
Cleanny/Cleanny/Pages/SettingSliderView.swift

SettingModalView페이지를 리팩토링 및 수정 하였습니다.
- 각 뷰의 표현방식을 LazyVGrid와 ForEach로 수정
- 뷰 세분화
- 카테고리 리스트 제이슨 파일을 생성하였습니다.
- 완료(dismiss)버튼 추가

Feature setting modal view

---

Cleanny/Cleanny/Pages/SettingModalView.swift

feat: SettingModalView Background  Color 적용

---

Cleanny/Cleanny.xcodeproj/project.pbxproj
Cleanny/Cleanny/Pages/CircularProgressBarView.swift
Cleanny/Cleanny/Pages/CircularProgressView.swift

fix: Circular ProgrssBar Background Color 수정

---

Cleanny/Cleanny.xcodeproj/project.pbxproj
Cleanny/Cleanny/Pages/BarChartView.swift
Cleanny/Cleanny/Pages/ChartView.swift
Cleanny/Cleanny/Pages/RecordView.swift

feat: Update RecordView

---

Cleanny/Cleanny/Data/Cleaning.swift
Cleanny/Cleanny/Data/CleaningDataStore.swift
Cleanny/Cleanny/Pages/CleaningButtonView.swift
Cleanny/Cleanny/Pages/CleaningCategoryProgress.swift
Cleanny/Cleanny/Pages/SettingCard.swift
Cleanny/Cleanny/Pages/SettingSlider.swift

- Percent 에 따른 버튼 이미지 색상을 변경하였습니다.

feat: Fix Button Image Color

---

Cleanny/Cleanny/Pages/BarChartView.swift
Cleanny/Cleanny/Pages/ChartView.swift

- 차트의 패딩을 추가하고 Shadow 색상을 변경 하였습니다.

feat: Fix CharView Shadow Color

---

Cleanny/Cleanny/Pages/SettingCard.swift

fix: SettingCard 변수이름 변경

---

Cleanny/Cleanny/Pages/CleaningButtonView.swift

- 햅틱 반응의 종류를 변경하였습니다.
- 버튼을 오래 누르고 있을때 버튼의 scale이 변경되도록 하였습니다.

Feature Detail Fix

---

Cleanny/Cleanny/Pages/CleaningButtonView.swift

- 버튼 클릭시 청소완료상태로 Percent를 업데이트 했습니다.

feat: Update Cleaning Complate

---

Cleanny/Cleanny/Pages/CleaningButtonView.swift

- Button 클릭시 Progress Bar 게이지 수정

Feature hot fix

---

Cleanny/Cleanny/Pages/CleaningButtonView.swift

- 버튼을 누르는 시간이 2초는 조금 긴거같아 1.5초로 수정하였습니다.

feat: Fix LongPressed seconds 2 -> 1.5

---

Cleanny/Cleanny/Data/MonthDataStore.swift
Cleanny/Cleanny/Pages/ChartView.swift
Cleanny/Cleanny/Pages/RecordView.swift

- 경고 메세지를 수정했습니다.
- 차트 뷰에서 한글로 나오도록 수정하였습니다.

feat: Fix warning & Detail

---

Cleanny/Cleanny/ContentView.swift
Cleanny/Cleanny/Data/CleaningDataStore.swift
Cleanny/Cleanny/Pages/CharacterView.swift
Cleanny/Cleanny/Pages/CleaningButtonView.swift
Cleanny/Cleanny/Pages/CleaningCategoryProgress.swift

- 청소완료 버튼을 클릭 할 경우 로티의 애니메이션이 변경되도록 수정하였습니다.

feat: Add Cleaning Button Clicked Change Lottie Animation

---

Cleanny/Cleanny/ContentView.swift
Cleanny/Cleanny/CoreData/Persistence.swift
Cleanny/Cleanny/Data/CleaningDataStore.swift
Cleanny/Cleanny/Data/Month.swift
Cleanny/Cleanny/Data/UserDataStore.swift
Cleanny/Cleanny/OnboardingView.swift
Cleanny/Cleanny/Pages/BarChartView.swift
Cleanny/Cleanny/Pages/CalendarView.swift
Cleanny/Cleanny/Pages/CharacterView.swift
Cleanny/Cleanny/Pages/ChartView.swift
Cleanny/Cleanny/Pages/CleaningButtonView.swift
Cleanny/Cleanny/Pages/CleaningCategoryProgress.swift
Cleanny/Cleanny/Pages/CleaningCategoryView.swift
Cleanny/Cleanny/Pages/LottieView.swift
Cleanny/Cleanny/Pages/RecordView.swift
Cleanny/Cleanny/Pages/SettingSliderView.swift
Cleanny/Cleanny/Pages/ShareView.swift

refeactor: Preview 정리

---

Cleanny/Cleanny.xcodeproj/project.pbxproj
Cleanny/Cleanny/Data/Cleaning.swift
Cleanny/Cleanny/Data/CleaningDataStore.swift
Cleanny/Cleanny/Pages/RecordButton.swift
Cleanny/Cleanny/Pages/RecordView.swift
Cleanny/Cleanny/Pages/SettingCard.swift
Cleanny/Cleanny/Pages/SettingSlider.swift

refactor: Record Button View 수정

---

Cleanny/Cleanny.xcodeproj/project.pbxproj
Cleanny/Cleanny.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Launch Screen에 사용한 SDWebImage 패키지가 누락되어 다시 커밋 합니다

fix: 패키지 추가

---

Cleanny/Cleanny/Views/CleaningButtonView.swift

- 캐릭터 뷰에서 버튼을 잠깐 눌렀다 취소할때 애니메이션과 카운트가 취소되도록 수정하였습니다.

feat: Fix LongPress Button Animation

---

Cleanny/Cleanny/ContentView.swift
Cleanny/Cleanny/Data/CleaningDataStore.swift
Cleanny/Cleanny/Views/CharacterView.swift
Cleanny/Cleanny/Views/Record/ChartPages/ChartPage1.swift
Cleanny/Cleanny/Views/Record/ChartPages/ChartPage2.swift
Cleanny/Cleanny/Views/Record/ChartPages/ChartPage3.swift
Cleanny/Cleanny/Views/Record/ChartPages/ChartPage4.swift
Cleanny/Cleanny/Views/Record/ChartPages/ChartPage5.swift
Cleanny/Cleanny/Views/Record/ChartPages/ChartPage6.swift

해결을 위해 array를 구하는 계산식의 볼륨을 줄였다.

feat: Fix chartButton 잔상
